#===== basic =====
# Default terminal is 256 colors
set -g default-terminal "screen-256color"
# Add truecolor support
set-option -ga terminal-overrides ",*256col*:Tc"

# Add mouse support
set-option -g mouse on

# 设置窗口面板起始序号
set -g base-index 1  # 设置窗口(window)的起始下标为1
set -g pane-base-index 1  # 设置面板(pane)的起始下标为1

# refresh status bar every second
set-option -g status-interval 1


#===== key bindings =====
# Use customize keys to splitting windows
# unbind-key %
# unbind-key '"'
bind | split-window -h
bind - split-window -v

# 面板(pane)切换
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r e lastp # 切换到最后使用的窗口 
bind -r C-u swap-pane -U # 与前一个面板交换位置
bind -r C-d swap-pane -D # 与后一个面板交换位置

# 调整面板大小：绑定 Shift + h/j/k/l 键调整pane边缘
bind -r K resizep -U 10 # upward (prefix Shift+k)
bind -r J resizep -D 10 # downward (prefix Shift+j)
bind -r H resizep -L 10 # to the left (prefix Shift+h)
bind -r L resizep -R 10 # to the right (prefix Shift+l)

# 这里是用x关闭面板的时候去除提示
# bind-key x kill-pane

# Easy config reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
