# Default terminal is 256 colors
set -g default-terminal "screen-256color"
# Add truecolor support
set-option -ga terminal-overrides ",*256col*:Tc"
# Add mouse support since v2.1
set-option -g mouse on
# 状态栏支持utf-8
set -g status-utf8 on
# 状态栏刷新时间
set -g status-interval 1 
